
package com.epam.lab.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12 2017-08-20T15:03:39.991+03:00
 * Generated source version: 3.1.12
 * 
 */
public final class CopterRemoteController_CopterRemoteControllerImpPort_Client {

	private static final QName SERVICE_NAME = new QName("http://service.lab.epam.com/",
			"CopterRemoteControllerImpService");

	private CopterRemoteController_CopterRemoteControllerImpPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = CopterRemoteControllerImpService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		CopterRemoteControllerImpService ss = new CopterRemoteControllerImpService(wsdlURL, SERVICE_NAME);
		CopterRemoteController port = ss.getCopterRemoteControllerImpPort();

		{
			System.out.println("Invoking moveUp...");
			com.epam.lab.service.Response _moveUp__return = port.moveUp();
			System.out.println("moveUp.result=" + _moveUp__return);

		}
		{
			System.out.println("Invoking moveBack...");
			com.epam.lab.service.Response _moveBack__return = port.moveBack();
			System.out.println("moveBack.result=" + _moveBack__return);

		}
		{
			System.out.println("Invoking moveDown...");
			com.epam.lab.service.Response _moveDown__return = port.moveDown();
			System.out.println("moveDown.result=" + _moveDown__return);

		}
		{
			System.out.println("Invoking stop...");
			com.epam.lab.service.Response _stop__return = port.stop();
			System.out.println("stop.result=" + _stop__return);

		}
		{
			System.out.println("Invoking moveForward...");
			com.epam.lab.service.Response _moveForward__return = port.moveForward();
			System.out.println("moveForward.result=" + _moveForward__return);

		}

		System.exit(0);
	}

}
