
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.epam.lab.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-20T15:03:40.108+03:00
 * Generated source version: 3.1.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "CopterRemoteControllerImpService",
                      portName = "CopterRemoteControllerImpPort",
                      targetNamespace = "http://service.lab.epam.com/",
                      wsdlLocation = "http://localhost:8080/RemoteControll/CopterRemoteControll?wsdl",
                      endpointInterface = "com.epam.lab.service.CopterRemoteController")
                      
public class CopterRemoteControllerImpPortImpl implements CopterRemoteController {

    private static final Logger LOG = Logger.getLogger(CopterRemoteControllerImpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.epam.lab.service.CopterRemoteController#moveUp()*
     */
    public com.epam.lab.service.Response moveUp() { 
        LOG.info("Executing operation moveUp");
        try {
            com.epam.lab.service.Response _return = new com.epam.lab.service.Response();
            _return.setMessage("Message-1425615042");
            com.epam.lab.service.Copter _returnCopter = new com.epam.lab.service.Copter();
            _returnCopter.setDistance(-1172424765);
            _returnCopter.setHeight(1801815914);
            _return.setCopter(_returnCopter);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epam.lab.service.CopterRemoteController#moveBack()*
     */
    public com.epam.lab.service.Response moveBack() { 
        LOG.info("Executing operation moveBack");
        try {
            com.epam.lab.service.Response _return = new com.epam.lab.service.Response();
            _return.setMessage("Message805248884");
            com.epam.lab.service.Copter _returnCopter = new com.epam.lab.service.Copter();
            _returnCopter.setDistance(417133956);
            _returnCopter.setHeight(-1519939992);
            _return.setCopter(_returnCopter);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epam.lab.service.CopterRemoteController#moveDown()*
     */
    public com.epam.lab.service.Response moveDown() { 
        LOG.info("Executing operation moveDown");
        try {
            com.epam.lab.service.Response _return = new com.epam.lab.service.Response();
            _return.setMessage("Message1700512749");
            com.epam.lab.service.Copter _returnCopter = new com.epam.lab.service.Copter();
            _returnCopter.setDistance(-585022841);
            _returnCopter.setHeight(-342510055);
            _return.setCopter(_returnCopter);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epam.lab.service.CopterRemoteController#stop()*
     */
    public com.epam.lab.service.Response stop() { 
        LOG.info("Executing operation stop");
        try {
            com.epam.lab.service.Response _return = new com.epam.lab.service.Response();
            _return.setMessage("Message-1048253722");
            com.epam.lab.service.Copter _returnCopter = new com.epam.lab.service.Copter();
            _returnCopter.setDistance(-1091994528);
            _returnCopter.setHeight(-1848687198);
            _return.setCopter(_returnCopter);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epam.lab.service.CopterRemoteController#moveForward()*
     */
    public com.epam.lab.service.Response moveForward() { 
        LOG.info("Executing operation moveForward");
        try {
            com.epam.lab.service.Response _return = new com.epam.lab.service.Response();
            _return.setMessage("Message-1210889941");
            com.epam.lab.service.Copter _returnCopter = new com.epam.lab.service.Copter();
            _returnCopter.setDistance(-1748950514);
            _returnCopter.setHeight(1314638055);
            _return.setCopter(_returnCopter);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
